
development: &development
 adapter: mysql2
 database: taskmanagement_development
 username: root
 password: root

test: &test
 adapter: mysql2
 database: taskmanagement_test
 username: travis
 encoding: utf8

production:
  adapter: postgresql
  database: taskmanagement_production
  pool: 5
  timeout: 5000

